### ISSUE TITLE
Resource fails with errors

### ISSUE THREAD

**Issue by haydonryan** [airtonix/concourse-resource-samba#2]
```
resource script '/opt/resource/check []' failed: exit status 127

stderr:
/opt/resource/check: line 8: soruce: command not found
```
Just thought i'd try this out and get the following error, looks like you have a typo, and have a few in the README.md too. - ie the example does not work as given, it should be more like this:

```
resource_types:
- name: samba-resource
  type: docker-image
  source:
      repository: airtonix/concourse-resource-samba
      tag: latest

resources:
- name: samba-resource
  type: samba-resource
  source:
    server: 
    share: Data
    user : 
    password:

jobs:
- name: the-big-payback
  plan:
  - get: samba-resource
    params: 
      path: _test
  - put: samba-resource
    params: 
      path: "_test2" 
```

Can you also indicate if this resource actually works or is in development
